"""Render isa_spec.OPS into the C header (isa/include/xdsp.h) and the manual (docs/XDSP_MANUAL.md)."""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path

from isaagent.isa_spec import CHAPTERS, OPS, TYPES

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "isa" / "include" / "xdsp.h"
MANUAL = ROOT / "docs" / "XDSP_MANUAL.md"


def signature(op: dict) -> str:
    return f"{op['ret']} {op['name']}({op['params']})"


def render_header() -> str:
    lines = [
        "/* xdsp.h - XDSP vector DSP operations (generated by isaagent/gen_isa.py, do not edit). */",
        "#ifndef XDSP_H",
        "#define XDSP_H",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "#include <math.h>",
        "#include <riscv_vector.h>",
        "",
    ]
    lines += [f"typedef {c} {t};" for t, c, _ in TYPES]
    lines.append("")
    for op in OPS:
        body = op["body"]
        lines.append(f"static inline __attribute__((always_inline)) {signature(op)} {{\n  {body}\n}}")
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def manual_entries() -> list[dict]:
    """One retrieval chunk per chapter and per operation."""
    chunks = [{"id": f"chapter:{k}", "title": k, "text": v} for k, v in CHAPTERS.items()]
    for op in OPS:
        chunks.append({
            "id": op["name"],
            "title": f"{op['name']} ({op['group']})",
            "text": f"`{signature(op)}`\n\n{op['doc']}",
        })
    return chunks


def render_manual() -> str:
    out = ["# XDSP Programmer's Reference Manual", "",
           "Generated from `isaagent/isa_spec.py`. This manual is the only specification of XDSP.", ""]
    for title, text in CHAPTERS.items():
        out += [f"## {title}", "", text, ""]
    groups: OrderedDict[str, list[dict]] = OrderedDict()
    for op in OPS:
        groups.setdefault(op["group"], []).append(op)
    out += ["## Operation reference", ""]
    for g, ops in groups.items():
        out += [f"### {g}", ""]
        for op in ops:
            out += [f"#### {op['name']}", "", f"`{signature(op)}`", "", op["doc"], ""]
    return "\n".join(out)


def main() -> None:
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    MANUAL.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(render_header())
    MANUAL.write_text(render_manual())
    print(f"wrote {HEADER} ({len(OPS)} ops) and {MANUAL}")


if __name__ == "__main__":
    main()
