"""Aggregate results/episodes.jsonl (+ baselines, MLIR flow) into docs/RESULTS.md, results/summary.json and figures."""

from __future__ import annotations

import collections
import json
import math
from pathlib import Path

from isaagent.agent import CONDITIONS
from isaagent.tasks import TASKS

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "results"
DOC = ROOT / "docs" / "RESULTS.md"
FIG = ROOT / "docs" / "figures"

LABEL = {
    "rvv_nodoc": "Public ISA (RVV intrinsics), no docs",
    "xdsp_nodoc": "Unseen ISA, no docs",
    "xdsp_full": "Unseen ISA, full manual in prompt",
    "xdsp_rag": "Unseen ISA, retrieved manual sections",
    "xdsp_agent": "Agent: retrieval + search tool + toolchain repair loop",
    "xdsp_opt": "Agent + optimisation loop (instruction counts)",
    "xdsp_rag_typed": "Unseen ISA, type-aware retrieval (core ops + examples)",
    "xdsp_agent_typed": "Agent with type-aware retrieval",
    "xdsp_opt_typed": "Agent with type-aware retrieval + optimisation loop",
}


def wilson(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (max(0.0, c - h), min(1.0, c + h))


def load() -> list[dict]:
    import os
    p = RES / "episodes.jsonl"
    eps = [json.loads(line) for line in p.read_text().splitlines()] if p.exists() else []
    only = os.environ.get("REPORT_MODELS")  # e.g. while a run for another model is still in progress
    return [e for e in eps if not only or e["model"] in only.split(",")]


def pct(k: int, n: int) -> str:
    if n == 0:
        return "-"
    lo, hi = wilson(k, n)
    return f"{k}/{n} = {100 * k / n:.0f}% [{100 * lo:.0f}-{100 * hi:.0f}]"


def summarise(eps: list[dict]) -> dict:
    out: dict = {}
    by = collections.defaultdict(list)
    for e in eps:
        by[(e["model"], e["condition"])].append(e)
    for (m, c), v in by.items():
        n = len(v)
        passed = [e for e in v if e["passed"]]
        out.setdefault(m, {})[c] = {
            "n": n,
            "pass": len(passed),
            "first_pass": sum(e["first_pass"] for e in v),
            "compiled_first": sum(e["compiled_first"] for e in v),
            "hallucinated_first": sum(bool(e["hallucinated_first"]) for e in v),
            "vectorized_pass": sum(e["vectorized"] for e in passed),
            "mean_llm_calls": sum(len([a for a in e["attempts"] if a["kind"] != "search"]) + len(e["searches"]) for e in v) / n,
            "mean_output_tokens": sum(e["output_tokens"] for e in v) / n,
            "mean_seconds": sum(e["seconds"] for e in v) / n,
            "tasks_solved_any_seed": len({e["task"] for e in passed}),
        }
    return out


def main() -> None:
    eps = load()
    base = json.loads((RES / "baselines.json").read_text())
    mlir = json.loads((RES / "mlir_flow.json").read_text()) if (RES / "mlir_flow.json").exists() else {}
    summ = summarise(eps)
    models = sorted(summ)
    L = ["# Results", "",
         "All numbers below are generated by `python -m isaagent.report` from `results/episodes.jsonl`, "
         "`results/baselines.json` and `results/mlir_flow.json`. Nothing is typed in by hand.", "",
         "Setup: 14 DSP kernels x 3 seeds per condition, local models served by Ollama on one NVIDIA L4 "
         "(temperature 0.4). Programs are compiled with clang 18 for RV64GCV and run on QEMU 8.2 "
         "(VLEN = 128). \"Pass\" = bit-exact (integer) or within tolerance (float) on every test case, including "
         "edge sizes and a forced-saturation case, with no writes past the output buffer. Brackets: Wilson 95% "
         "interval. Costs are dynamic instruction counts inside the kernel on QEMU, NOT cycles.", ""]
    for m in models:
        L += [f"## {m}", "", "| Condition | Pass (any attempt) | Pass first try | First program compiles | "
              "Invented identifiers in first program | Vectorised passes | LLM calls / episode | Output tokens / episode | "
              "Seconds / episode | Tasks solved (any seed) |", "|---|---|---|---|---|---|---|---|---|---|"]
        for c in CONDITIONS:
            s = summ[m].get(c)
            if not s:
                continue
            L.append(f"| {LABEL[c]} | {pct(s['pass'], s['n'])} | {pct(s['first_pass'], s['n'])} | "
                     f"{pct(s['compiled_first'], s['n'])} | {pct(s['hallucinated_first'], s['n'])} | "
                     f"{s['vectorized_pass']}/{s['pass']} | {s['mean_llm_calls']:.1f} | {s['mean_output_tokens']:.0f} | "
                     f"{s['mean_seconds']:.0f} | {s['tasks_solved_any_seed']}/14 |")
        L.append("")

    # per-task table for the agentic conditions
    for m in models:
        L += [f"### Per task, {m}", "", "Pass counts out of 3 seeds, and the best passing agent kernel's cost relative to "
              "compiler auto-vectorisation at the same register width (LMUL = 1; < 1.00 = fewer instructions than "
              "the compiler).", "",
              "| Task | no docs | full manual | retrieval | agent | agent + opt | typed retrieval | typed agent | typed agent + opt "
              "| best agent insns | vs clang autovec (LMUL=1) | vs hand-written XDSP | vs scalar -O2 |",
              "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
        for t in TASKS:
            row = [t.name]
            for c in ["xdsp_nodoc", "xdsp_full", "xdsp_rag", "xdsp_agent", "xdsp_opt", "xdsp_rag_typed", "xdsp_agent_typed", "xdsp_opt_typed"]:
                v = [e for e in eps if e["model"] == m and e["condition"] == c and e["task"] == t.name]
                row.append(f"{sum(e['passed'] for e in v)}/{len(v)}" if v else "-")
            best = [e["insns"] for e in eps if e["model"] == m and e["task"] == t.name and e["condition"].startswith(("xdsp_agent", "xdsp_opt"))
                    and e["passed"] and e["vectorized"] and e["insns"]]
            b = base[t.name]
            if best:
                bi = min(best)
                row += [str(bi), f"{bi / b['autovec_m1']:.2f}", f"{bi / b['expert_xdsp']:.2f}", f"{bi / b['scalar']:.2f}"]
            else:
                row += ["no vectorised pass", "-", "-", "-"]
            L.append("| " + " | ".join(row) + " |")
        L.append("")

    # optimisation loop effect
    opt = [e for e in eps if e["condition"].startswith("xdsp_opt") and e["passed"] and e["insns_first_pass"] and e["insns"]]
    if opt:
        improved = [e for e in opt if e["insns"] < e["insns_first_pass"]]
        L += ["## Optimisation loop", "",
              f"Episodes in the optimisation condition that passed: {len(opt)}. The optimisation rounds found a faster "
              f"correct kernel in {len(improved)} of them.", "",
              "| Model | Task | seed | first correct (insns) | after optimisation | change |", "|---|---|---|---|---|---|"]
        for e in sorted(improved, key=lambda e: (e["model"], e["task"], e["seed"])):
            L.append(f"| {e['model']} | {e['task']} | {e['seed']} | {e['insns_first_pass']} | {e['insns']} | "
                     f"{100 * (e['insns'] / e['insns_first_pass'] - 1):+.0f}% |")
        L.append("")

    # hallucinations
    names = collections.Counter(n for e in eps for n in e["hallucinated_first"] if e["condition"].startswith("xdsp"))
    if names:
        L += ["## Most frequent invented identifiers (first program, XDSP conditions)", "",
              "| Identifier | Count |", "|---|---|"] + [f"| `{k}` | {v} |" for k, v in names.most_common(15)] + [""]

    # baselines
    L += ["## Baselines (instructions for one call, bench input)", "",
          "| Task | n | scalar C -O2 | clang -O3 autovec | clang -O3 autovec, LMUL=1 | hand-written XDSP |", "|---|---|---|---|---|---|"]
    for t in TASKS:
        b = base[t.name]
        L.append(f"| {t.name} | {t.bench_n} | {b['scalar']} | {b['autovec']} | {b['autovec_m1']} | {b['expert_xdsp']} |")
    L.append("")
    if mlir:
        L += ["## ONNX -> MLIR -> LLVM -> RISC-V (float FIR, 16 taps, 1024 outputs; axpy, 1024)", "",
              "| Path | FIR insns | axpy insns | numerics vs onnxruntime |", "|---|---|---|---|"]
        tags = sorted({k.split("/", 1)[1] for k in mlir})
        for tag in tags:
            f, a = mlir.get(f"fir_f32/{tag}", {}), mlir.get(f"axpy_f32/{tag}", {})
            err = f.get("max_rel_err_vs_onnxruntime")
            L.append(f"| {tag} | {f.get('insns', '-')} | {a.get('insns', '-')} | "
                     f"{f'max rel err {err:.1e}' if err is not None else ('pass' if f.get('ok') else '-')} |")
        L.append("")
    readme_block(summ, base, mlir, eps)
    DOC.write_text("\n".join(L).replace("—", "-").replace("–", "-"))
    (RES / "summary.json").write_text(json.dumps(summ, indent=1))
    try:
        figures(summ)
    except ImportError:
        pass
    print(f"wrote {DOC}")


def readme_block(summ: dict, base: dict, mlir: dict, eps: list[dict]) -> None:
    """Rewrite the README section between the results markers from the same data."""
    readme = ROOT / "README.md"
    if not readme.exists():
        return
    txt = readme.read_text()
    a, b = "<!-- results:start -->", "<!-- results:end -->"
    if a not in txt:
        return
    R = ["", "| Condition | " + " | ".join(f"{m}: pass" for m in sorted(summ)) + " |",
         "|---|" + "---|" * len(summ)]
    for c in CONDITIONS:
        cells = []
        for m in sorted(summ):
            s = summ[m].get(c)
            cells.append(pct(s["pass"], s["n"]) if s else "-")
        R.append(f"| {LABEL[c]} | " + " | ".join(cells) + " |")
    R += ["", "Pass = bit-exact on every test case (14 kernels x 3 seeds per cell; Wilson 95% interval in brackets). "
          "Full tables, per-task results, the optimisation loop and baselines: [docs/RESULTS.md](docs/RESULTS.md).", ""]
    new = txt[: txt.index(a) + len(a)] + "\n".join(R) + txt[txt.index(b):]
    readme.write_text(new)


def figures(summ: dict) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    FIG.mkdir(parents=True, exist_ok=True)
    models = sorted(summ)
    conds = [c for c in CONDITIONS if any(c in summ[m] for m in models)]
    fig, ax = plt.subplots(figsize=(10.5, 4.4))
    w = 0.8 / max(1, len(models))
    for i, m in enumerate(models):
        ys, errs = [], [[], []]
        for c in conds:
            s = summ[m].get(c, {"pass": 0, "n": 0})
            p = s["pass"] / s["n"] if s["n"] else 0
            lo, hi = wilson(s["pass"], s["n"])
            ys.append(100 * p)
            errs[0].append(100 * (p - lo))
            errs[1].append(100 * (hi - p))
        ax.bar([j + i * w for j in range(len(conds))], ys, w, yerr=errs, capsize=3, label=m)
    ax.set_xticks([j + w * (len(models) - 1) / 2 for j in range(len(conds))])
    short = {"rvv_nodoc": "RVV\nno docs", "xdsp_nodoc": "no docs", "xdsp_full": "full\nmanual", "xdsp_rag": "retrieval",
             "xdsp_agent": "agent", "xdsp_opt": "agent\n+opt", "xdsp_rag_typed": "typed\nretrieval",
             "xdsp_agent_typed": "typed\nagent", "xdsp_opt_typed": "typed\nagent+opt"}
    ax.set_xticklabels([short[c] for c in conds], fontsize=8)
    ax.set_ylabel("episodes passing (%)")
    ax.set_ylim(0, 100)
    ax.legend(frameon=False)
    ax.set_title("Correct DSP kernels for an unseen vector ISA (14 tasks x 3 seeds)")
    fig.tight_layout()
    fig.savefig(FIG / "pass_rates.png", dpi=150)


if __name__ == "__main__":
    main()
