/* xdsp.h - XDSP vector DSP operations (generated by isaagent/gen_isa.py, do not edit). */
#ifndef XDSP_H
#define XDSP_H
#include <stddef.h>
#include <stdint.h>
#include <math.h>
#include <riscv_vector.h>

typedef vint16m1_t xd_h;
typedef vint32m2_t xd_w;
typedef vint32m1_t xd_s;
typedef vfloat32m1_t xd_f;
typedef vbool16_t xd_hmask;
typedef vbool32_t xd_smask;

static inline __attribute__((always_inline)) size_t xd_hlen(size_t n) {
  return __riscv_vsetvl_e16m1(n);
}
static inline __attribute__((always_inline)) size_t xd_hmaxlen(void) {
  return __riscv_vsetvlmax_e16m1();
}
static inline __attribute__((always_inline)) size_t xd_slen(size_t n) {
  return __riscv_vsetvl_e32m1(n);
}
static inline __attribute__((always_inline)) size_t xd_smaxlen(void) {
  return __riscv_vsetvlmax_e32m1();
}
static inline __attribute__((always_inline)) xd_h xd_hload(const int16_t *p, size_t vl) {
  return __riscv_vle16_v_i16m1(p, vl);
}
static inline __attribute__((always_inline)) void xd_hstore(int16_t *p, xd_h v, size_t vl) {
  __riscv_vse16_v_i16m1(p, v, vl);
}
static inline __attribute__((always_inline)) xd_h xd_hload_step(const int16_t *p, ptrdiff_t step, size_t vl) {
  return __riscv_vlse16_v_i16m1(p, step * (ptrdiff_t)sizeof(int16_t), vl);
}
static inline __attribute__((always_inline)) void xd_hload_iq(const int16_t *p, xd_h *i_out, xd_h *q_out, size_t vl) {
  vint16m1x2_t t = __riscv_vlseg2e16_v_i16m1x2(p, vl);
  *i_out = __riscv_vget_v_i16m1x2_i16m1(t, 0);
  *q_out = __riscv_vget_v_i16m1x2_i16m1(t, 1);
}
static inline __attribute__((always_inline)) void xd_hstore_iq(int16_t *p, xd_h i_in, xd_h q_in, size_t vl) {
  vint16m1x2_t t = __riscv_vset_v_i16m1_i16m1x2(__riscv_vundefined_i16m1x2(), 0, i_in);
  t = __riscv_vset_v_i16m1_i16m1x2(t, 1, q_in);
  __riscv_vsseg2e16_v_i16m1x2(p, t, vl);
}
static inline __attribute__((always_inline)) xd_h xd_hdup(int16_t x, size_t vl) {
  return __riscv_vmv_v_x_i16m1(x, vl);
}
static inline __attribute__((always_inline)) xd_h xd_hadd(xd_h a, xd_h b, size_t vl) {
  return __riscv_vadd_vv_i16m1(a, b, vl);
}
static inline __attribute__((always_inline)) xd_h xd_hsub(xd_h a, xd_h b, size_t vl) {
  return __riscv_vsub_vv_i16m1(a, b, vl);
}
static inline __attribute__((always_inline)) xd_h xd_haddsat(xd_h a, xd_h b, size_t vl) {
  return __riscv_vsadd_vv_i16m1(a, b, vl);
}
static inline __attribute__((always_inline)) xd_h xd_hsubsat(xd_h a, xd_h b, size_t vl) {
  return __riscv_vssub_vv_i16m1(a, b, vl);
}
static inline __attribute__((always_inline)) xd_h xd_havg(xd_h a, xd_h b, size_t vl) {
  return __riscv_vaadd_vv_i16m1(a, b, __RISCV_VXRM_RNU, vl);
}
static inline __attribute__((always_inline)) xd_h xd_hmul(xd_h a, xd_h b, size_t vl) {
  return __riscv_vmul_vv_i16m1(a, b, vl);
}
static inline __attribute__((always_inline)) xd_h xd_hqmul(xd_h a, xd_h b, size_t vl) {
  return __riscv_vsmul_vv_i16m1(a, b, __RISCV_VXRM_RNU, vl);
}
static inline __attribute__((always_inline)) xd_h xd_hqmulx(xd_h a, int16_t k, size_t vl) {
  return __riscv_vsmul_vx_i16m1(a, k, __RISCV_VXRM_RNU, vl);
}
static inline __attribute__((always_inline)) xd_h xd_hmax(xd_h a, xd_h b, size_t vl) {
  return __riscv_vmax_vv_i16m1(a, b, vl);
}
static inline __attribute__((always_inline)) xd_h xd_hmin(xd_h a, xd_h b, size_t vl) {
  return __riscv_vmin_vv_i16m1(a, b, vl);
}
static inline __attribute__((always_inline)) xd_h xd_habssat(xd_h a, size_t vl) {
  return __riscv_vmax_vv_i16m1(a, __riscv_vssub_vv_i16m1(__riscv_vmv_v_x_i16m1(0, vl), a, vl), vl);
}
static inline __attribute__((always_inline)) xd_h xd_hsra(xd_h a, unsigned sh, size_t vl) {
  return __riscv_vsra_vx_i16m1(a, sh, vl);
}
static inline __attribute__((always_inline)) xd_h xd_hsrar(xd_h a, unsigned sh, size_t vl) {
  return __riscv_vssra_vx_i16m1(a, sh, __RISCV_VXRM_RNU, vl);
}
static inline __attribute__((always_inline)) xd_h xd_hslide(xd_h a, size_t k, size_t vl) {
  return __riscv_vslidedown_vx_i16m1(a, k, vl);
}
static inline __attribute__((always_inline)) xd_hmask xd_hgt(xd_h a, xd_h b, size_t vl) {
  return __riscv_vmsgt_vv_i16m1_b16(a, b, vl);
}
static inline __attribute__((always_inline)) xd_hmask xd_hgtx(xd_h a, int16_t x, size_t vl) {
  return __riscv_vmsgt_vx_i16m1_b16(a, x, vl);
}
static inline __attribute__((always_inline)) xd_hmask xd_heqx(xd_h a, int16_t x, size_t vl) {
  return __riscv_vmseq_vx_i16m1_b16(a, x, vl);
}
static inline __attribute__((always_inline)) xd_h xd_hsel(xd_hmask m, xd_h if_true, xd_h if_false, size_t vl) {
  return __riscv_vmerge_vvm_i16m1(if_false, if_true, m, vl);
}
static inline __attribute__((always_inline)) size_t xd_hcount(xd_hmask m, size_t vl) {
  return (size_t)__riscv_vcpop_m_b16(m, vl);
}
static inline __attribute__((always_inline)) long xd_hfirst(xd_hmask m, size_t vl) {
  return __riscv_vfirst_m_b16(m, vl);
}
static inline __attribute__((always_inline)) int16_t xd_hredmax(xd_h a, size_t vl) {
  return __riscv_vmv_x_s_i16m1_i16(__riscv_vredmax_vs_i16m1_i16m1(a, __riscv_vmv_v_x_i16m1(-32768, 1), vl));
}
static inline __attribute__((always_inline)) int32_t xd_hredsum_w(xd_h a, size_t vl) {
  return __riscv_vmv_x_s_i32m1_i32(__riscv_vwredsum_vs_i16m1_i32m1(a, __riscv_vmv_v_x_i32m1(0, 1), vl));
}
static inline __attribute__((always_inline)) xd_w xd_wdup(int32_t x, size_t vl) {
  return __riscv_vmv_v_x_i32m2(x, vl);
}
static inline __attribute__((always_inline)) xd_w xd_wwiden(xd_h a, size_t vl) {
  return __riscv_vsext_vf2_i32m2(a, vl);
}
static inline __attribute__((always_inline)) xd_w xd_wmul(xd_h a, xd_h b, size_t vl) {
  return __riscv_vwmul_vv_i32m2(a, b, vl);
}
static inline __attribute__((always_inline)) xd_w xd_wmulx(xd_h a, int16_t k, size_t vl) {
  return __riscv_vwmul_vx_i32m2(a, k, vl);
}
static inline __attribute__((always_inline)) xd_w xd_wmac(xd_w acc, xd_h a, xd_h b, size_t vl) {
  return __riscv_vwmacc_vv_i32m2_tu(acc, a, b, vl);
}
static inline __attribute__((always_inline)) xd_w xd_wmacx(xd_w acc, int16_t k, xd_h a, size_t vl) {
  return __riscv_vwmacc_vx_i32m2_tu(acc, k, a, vl);
}
static inline __attribute__((always_inline)) xd_w xd_wadd(xd_w a, xd_w b, size_t vl) {
  return __riscv_vadd_vv_i32m2(a, b, vl);
}
static inline __attribute__((always_inline)) xd_w xd_wsub(xd_w a, xd_w b, size_t vl) {
  return __riscv_vsub_vv_i32m2(a, b, vl);
}
static inline __attribute__((always_inline)) xd_w xd_wsra(xd_w a, unsigned sh, size_t vl) {
  return __riscv_vsra_vx_i32m2(a, sh, vl);
}
static inline __attribute__((always_inline)) xd_h xd_wnarrow(xd_w a, unsigned sh, size_t vl) {
  return __riscv_vnclip_wx_i16m1(a, sh, __RISCV_VXRM_RNU, vl);
}
static inline __attribute__((always_inline)) int32_t xd_wredsum(xd_w a, size_t vl) {
  return __riscv_vmv_x_s_i32m1_i32(__riscv_vredsum_vs_i32m2_i32m1(a, __riscv_vmv_v_x_i32m1(0, 1), vl));
}
static inline __attribute__((always_inline)) xd_w xd_wload(const int32_t *p, size_t vl) {
  return __riscv_vle32_v_i32m2(p, vl);
}
static inline __attribute__((always_inline)) void xd_wstore(int32_t *p, xd_w v, size_t vl) {
  __riscv_vse32_v_i32m2(p, v, vl);
}
static inline __attribute__((always_inline)) xd_hmask xd_wgtx(xd_w a, int32_t x, size_t vl) {
  return __riscv_vmsgt_vx_i32m2_b16(a, x, vl);
}
static inline __attribute__((always_inline)) xd_s xd_sload(const int32_t *p, size_t vl) {
  return __riscv_vle32_v_i32m1(p, vl);
}
static inline __attribute__((always_inline)) void xd_sstore(int32_t *p, xd_s v, size_t vl) {
  __riscv_vse32_v_i32m1(p, v, vl);
}
static inline __attribute__((always_inline)) xd_s xd_sdup(int32_t x, size_t vl) {
  return __riscv_vmv_v_x_i32m1(x, vl);
}
static inline __attribute__((always_inline)) xd_s xd_sadd(xd_s a, xd_s b, size_t vl) {
  return __riscv_vadd_vv_i32m1(a, b, vl);
}
static inline __attribute__((always_inline)) xd_s xd_ssub(xd_s a, xd_s b, size_t vl) {
  return __riscv_vsub_vv_i32m1(a, b, vl);
}
static inline __attribute__((always_inline)) xd_s xd_smul(xd_s a, xd_s b, size_t vl) {
  return __riscv_vmul_vv_i32m1(a, b, vl);
}
static inline __attribute__((always_inline)) xd_s xd_smulx(xd_s a, int32_t k, size_t vl) {
  return __riscv_vmul_vx_i32m1(a, k, vl);
}
static inline __attribute__((always_inline)) xd_s xd_ssra(xd_s a, unsigned sh, size_t vl) {
  return __riscv_vsra_vx_i32m1(a, sh, vl);
}
static inline __attribute__((always_inline)) xd_s xd_smax(xd_s a, xd_s b, size_t vl) {
  return __riscv_vmax_vv_i32m1(a, b, vl);
}
static inline __attribute__((always_inline)) xd_smask xd_sgt(xd_s a, xd_s b, size_t vl) {
  return __riscv_vmsgt_vv_i32m1_b32(a, b, vl);
}
static inline __attribute__((always_inline)) xd_smask xd_sgtx(xd_s a, int32_t x, size_t vl) {
  return __riscv_vmsgt_vx_i32m1_b32(a, x, vl);
}
static inline __attribute__((always_inline)) xd_s xd_ssel(xd_smask m, xd_s if_true, xd_s if_false, size_t vl) {
  return __riscv_vmerge_vvm_i32m1(if_false, if_true, m, vl);
}
static inline __attribute__((always_inline)) size_t xd_scount(xd_smask m, size_t vl) {
  return (size_t)__riscv_vcpop_m_b32(m, vl);
}
static inline __attribute__((always_inline)) int32_t xd_sredsum(xd_s a, size_t vl) {
  return __riscv_vmv_x_s_i32m1_i32(__riscv_vredsum_vs_i32m1_i32m1(a, __riscv_vmv_v_x_i32m1(0, 1), vl));
}
static inline __attribute__((always_inline)) int32_t xd_sredmax(xd_s a, size_t vl) {
  return __riscv_vmv_x_s_i32m1_i32(__riscv_vredmax_vs_i32m1_i32m1(a, __riscv_vmv_v_x_i32m1(INT32_MIN, 1), vl));
}
static inline __attribute__((always_inline)) xd_f xd_fload(const float *p, size_t vl) {
  return __riscv_vle32_v_f32m1(p, vl);
}
static inline __attribute__((always_inline)) void xd_fstore(float *p, xd_f v, size_t vl) {
  __riscv_vse32_v_f32m1(p, v, vl);
}
static inline __attribute__((always_inline)) xd_f xd_fdup(float x, size_t vl) {
  return __riscv_vfmv_v_f_f32m1(x, vl);
}
static inline __attribute__((always_inline)) xd_f xd_fadd(xd_f a, xd_f b, size_t vl) {
  return __riscv_vfadd_vv_f32m1(a, b, vl);
}
static inline __attribute__((always_inline)) xd_f xd_fsub(xd_f a, xd_f b, size_t vl) {
  return __riscv_vfsub_vv_f32m1(a, b, vl);
}
static inline __attribute__((always_inline)) xd_f xd_fmul(xd_f a, xd_f b, size_t vl) {
  return __riscv_vfmul_vv_f32m1(a, b, vl);
}
static inline __attribute__((always_inline)) xd_f xd_fmulx(xd_f a, float k, size_t vl) {
  return __riscv_vfmul_vf_f32m1(a, k, vl);
}
static inline __attribute__((always_inline)) xd_f xd_faddx(xd_f a, float k, size_t vl) {
  return __riscv_vfadd_vf_f32m1(a, k, vl);
}
static inline __attribute__((always_inline)) xd_f xd_fmac(xd_f acc, xd_f a, xd_f b, size_t vl) {
  return __riscv_vfmacc_vv_f32m1_tu(acc, a, b, vl);
}
static inline __attribute__((always_inline)) xd_f xd_fmacx(xd_f acc, float k, xd_f a, size_t vl) {
  return __riscv_vfmacc_vf_f32m1_tu(acc, k, a, vl);
}
static inline __attribute__((always_inline)) float xd_fredsum(xd_f a, size_t vl) {
  return __riscv_vfmv_f_s_f32m1_f32(__riscv_vfredusum_vs_f32m1_f32m1(a, __riscv_vfmv_v_f_f32m1(0.0f, 1), vl));
}
static inline __attribute__((always_inline)) float xd_fredmax(xd_f a, size_t vl) {
  return __riscv_vfmv_f_s_f32m1_f32(__riscv_vfredmax_vs_f32m1_f32m1(a, __riscv_vfmv_v_f_f32m1(-INFINITY, 1), vl));
}

#endif
